name: app_library_workspace
publish_to: none

environment:
  sdk: ^3.7.0

workspace:
  - apps/showcase
  - packages/ui_kit
  - packages/core
  - packages/l10n
  - packages/notifications
  - packages/theme
  - packages/supabase_client
  - packages/pagination
  - packages/cache
  - packages/error_logging
  - packages/auth
  - packages/comments
