import '../models/qt_passage.dart';

/// Abstract QT passages repository
abstract class QtRepository {
  /// Get today's QT passages (5 passages generated by cronjob)
  Future<List<QTPassage>> getTodayPassages();
}
