name: app_lib_notifications
description: App Library notifications package.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  app_lib_core:
    path: ../core
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
