name: showcase
description: App Library component showcase app.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  flutter_riverpod: ">=3.0.0 <3.2.0"
  app_lib_core:
  app_lib_theme:
  app_lib_ui_kit:
  app_lib_auth:
  app_lib_comments:
  app_lib_pagination:
flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
